"""Content-addressable blob cache for extracted Z-Wave specification data."""

from __future__ import annotations

import hashlib
import json
import logging
import shutil
from pathlib import Path
from typing import Any

from mcp_zwave_specs.config import Config

logger = logging.getLogger(__name__)

_HASH_SKIP_DIRS = frozenset({".git", "__pycache__", ".venv", "node_modules"})


# ---------------------------------------------------------------------------
# Public hash helpers
# ---------------------------------------------------------------------------


def file_hash(path: Path) -> str:
    """16-char hex hash of a file's content. Deterministic across machines."""
    return hashlib.md5(path.read_bytes()).hexdigest()[:16]


def dir_hash(dir_path: Path, extensions: frozenset[str] | None = None) -> str:
    """16-char hex hash of all matching files' content in a directory.

    Skips directories listed in ``_HASH_SKIP_DIRS``.
    """
    h = hashlib.md5()
    for p in sorted(dir_path.rglob("*")):
        if any(part in _HASH_SKIP_DIRS for part in p.parts):
            continue
        if p.is_file() and (extensions is None or p.suffix.lower() in extensions):
            h.update(str(p.relative_to(dir_path)).encode())
            h.update(p.read_bytes())
    return h.hexdigest()[:16]


# ---------------------------------------------------------------------------
# CacheManager
# ---------------------------------------------------------------------------


class CacheManager:
    """Content-addressable blob cache.

    Cache slots live under ``cache_dir/<hash16>/``.

    Each slot can hold:
    * ``data.json`` -- primary JSON payload
    * ``meta.json`` -- optional metadata
    * ``data/``     -- arbitrary sub-files (text)
    """

    def __init__(self, config: Config) -> None:
        self.config = config
        self.cache_dir = config.cache_dir

    def _slot(self, key: str) -> Path:
        return self.cache_dir / key

    def has_blob(self, key: str) -> bool:
        """Return True if a blob slot exists for *key*."""
        return self._slot(key).is_dir()

    def read_blob(self, key: str) -> Any | None:
        """Read ``data.json`` from a blob slot, or ``None`` on miss."""
        path = self._slot(key) / "data.json"
        if not path.exists():
            return None
        try:
            return json.loads(path.read_text())
        except (json.JSONDecodeError, OSError):
            logger.warning("Failed to read blob %s/data.json, ignoring", key)
            return None

    def write_blob(self, key: str, data: Any, meta: dict | None = None) -> None:
        """Write ``data.json`` (and optional ``meta.json``) into a blob slot."""
        slot = self._slot(key)
        slot.mkdir(parents=True, exist_ok=True)
        (slot / "data.json").write_text(json.dumps(data, indent=2, ensure_ascii=False))
        if meta is not None:
            (slot / "meta.json").write_text(json.dumps(meta, indent=2, ensure_ascii=False))

    def read_blob_text(self, key: str, rel_path: str) -> str | None:
        """Read ``data/<rel_path>`` from a blob slot, or ``None`` on miss."""
        path = self._slot(key) / "data" / rel_path
        if not path.exists():
            return None
        try:
            return path.read_text()
        except OSError:
            return None

    def write_blob_text(self, key: str, rel_path: str, text: str) -> None:
        """Write ``data/<rel_path>`` into a blob slot."""
        path = self._slot(key) / "data" / rel_path
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text)

    def clear(self) -> None:
        """Remove all cached data."""
        if self.cache_dir.exists():
            shutil.rmtree(self.cache_dir)
        logger.info("Cache cleared: %s", self.cache_dir)

    def write_gitignore(self) -> None:
        """Write ``.gitignore`` tracking current blobs, ignoring future ones."""
        if not self.cache_dir.exists():
            return
        blob_dirs = sorted(
            d.name
            for d in self.cache_dir.iterdir()
            if d.is_dir() and len(d.name) == 16 and all(c in "0123456789abcdef" for c in d.name)
        )
        lines = [
            "# Auto-generated — tracks pre-built cache blobs",
            "# Regenerated by --write-gitignore",
            "",
            "# Default: ignore all",
            "*",
            "",
            "# Track this file",
            "!.gitignore",
        ]
        if blob_dirs:
            lines.append("")
            lines.append("# Pre-built blobs (deterministic content hashes)")
            for d in blob_dirs:
                lines.append(f"!{d}/")
                lines.append(f"!{d}/**")
        lines.append("")
        (self.cache_dir / ".gitignore").write_text("\n".join(lines))
